type User @table {
  username: String!
  email: String!
  passwordHash: String!
  createdAt: Timestamp!
  displayName: String
  bio: String
  profilePictureUrl: String
}

type Post @table {
  content: String!
  createdAt: Timestamp!
  imageUrl: String
  author: User
}

type Comment @table {
  content: String!
  createdAt: Timestamp!
  author: User
  post: Post
}

type Like @table {
  createdAt: Timestamp!
  user: User
  post: Post
}

type Follow @table(key: ["follower", "followee"]) {
  createdAt: Timestamp!
  follower: User!
  followee: User!
}